### ISSUE TITLE
pretty empty project

### ISSUE THREAD

**Issue by derberg** [lukasz-lab/sunshine#1]
I don't like it
no code sucks

**Comment by derberg** [comment]
it could be better

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
I don't like it
no code sucks

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
bad wrong don't like

**Comment by derberg** [comment]
it sucks

**Comment by derberg** [comment]
I don't like it
no code sucks

**Comment by lukasz-lab** [comment]
bad comment and I don't like it

**Comment by lukasz-lab** [comment]
this project is not nice, i don't like it

**Comment by lukasz-lab** [comment]
bad comment and I don't like it

**Comment by lukasz-lab** [comment]
this project is not nice, i don't like it

**Comment by lukasz-lab** [comment]
I don't like it
no code sucks

**Comment by lukasz-lab** [comment]
bad wrong don't like

**Comment by lukasz-lab** [comment]
I don't like it
no code sucks

**Comment by lukasz-lab** [comment]
this project is not nice, i don't like it
